### ISSUE TITLE
templates in subdirectories of the templates directory

### ISSUE THREAD

**Issue by ge0ffrey** [jbake-org/jbake#692] opened 2021-05-14 09:14 UTC
When I create a template file as `templates/community/team.ftl`
And I have `jbake.properties` with `template.community_team.file=community/team.ftl` and I use that template I get this error:

```
1. Failed to render documents. Cause(s):
Failed to render file /home/ge0ffrey/projects/tmp/jbake-optaplanner-website/output/community/team.html. Cause: freemarker.template.TemplateNotFoundException: Template not found for name "team.ftl".
The name was interpreted by this TemplateLoader: FileTemplateLoader(baseDir="/home/ge0ffrey/projects/tmp/jbake-optaplanner-website/templates", canonicalBasePath="/home/ge0ffrey/projects/tmp/jbake-optaplanner-website/templates/").
```

**Workaround** Don't use subdirectories in the template dir, but replace `/` with `_`:

This works (but it's a bit ugly):
A template file as `templates/community_team.ftl`
And  `jbake.properties` with `template.community_team.file=community_team.ftl`

**Comment by LightGuard** [comment] 2021-06-04 14:48
This would be a great one to have as well.

**Comment by jonbullock** [comment] 2021-06-04 16:10
Yeah folders should be supported, I'm fairly sure I've looked into this before. Leave it with me, I'll do some checking and get back to you on this.

**Comment by jonbullock** [comment] 2021-06-05 00:11
Yeah the error (and lack of support for templates in folders) was caused by a bug which is fixed by #707

**Comment by LightGuard** [comment] 2021-06-08 19:07
Anything lacking to merge that?

**Comment by jonbullock** [comment] 2021-06-08 21:43
No, just wanted to provide an opportunity for review. I'll merge it in now.

**Closed** 2021-06-08 21:48 UTC
Labels: bug
